version: "3.8"

services:
  database:
    image: postgres:15
    container_name: wiki-postgres
    restart: always
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: wikiuser
      POSTGRES_PASSWORD: wikisecret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  wiki:
    image: requarks/wiki:latest
    container_name: wiki-js
    restart: always
    depends_on:
      - database
    environment:
      DB_TYPE: postgres
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: wikiuser
      DB_PASS: wikisecret
      DB_NAME: wiki
    ports:
      - "3000:3000"

volumes:
  pgdata:

    